### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by HanSolo72** [bntan/tesla-tokens#1]
Hi, I installed Python 3 on Windows 10 in the Path C:\Python30 and then I opened the Python command line. But how can I download dependencies ($ pip install -r requirements.txt).

I have the following questions, please enhance your readme.
- Is $ the prompt or part of the command?
- Where should I place the requirements.txt and tesla-tokens.py?
- How can I execute the command $ python tesla-tokens.py?

**Comment by coronawalrus** [comment]
May I suggest learning Python basics before trying to play some random code ?
https://www.python.org/about/gettingstarted/

**Comment by HanSolo72** [comment]
I don't want to learn Python, I just want to get a Token for my Tesla. I would appreciate an instruction that works also for people who aren't familiar with Python.

**Comment by bntan** [comment]
Hi,

Below the answers to the questions:
- Once tesla-tokens repository cloned on your computer, open a command line (cmd in Windows) and go to tesla-tokens directory. This directory contains requirements.txt and tesla-tokens.py
- You can then download the dependencies by excuting `pip install -r requirements.txt` in the command line
- $ is the prompt. Do not type $ in your command
- You can then launch the script by executing `python tesla-tokens.py` in the command line

Hope this helps!

**Comment by coronawalrus** [comment]
May I therefore suggest calling Tesla official support, in order to get a quotation for a complete product?

**Comment by HanSolo72** [comment]
> May I therefore suggest calling Tesla official support, in order to get a quotation for a complete product?

Why don't you keep quiet if you don't have anything useful to contribute?

**Comment by HanSolo72** [comment]
> * Once tesla-tokens repository cloned on your computer, open a command line (cmd in Windows) and go to tesla-tokens directory. This directory contains requirements.txt and tesla-tokens.py
> * You can then download the dependencies by excuting `pip install -r requirements.txt` in the command line
> * $ is the prompt. Do not type $ in your command
> * You can then launch the script by executing `python tesla-tokens.py` in the command line

Hi,

yes, it helped. My first mistake was to install Python 3.0 instead of 3.10. The pip command worked after I found the path where pip.exe was stored. But when I call python.exe (stored in the path C:\Users\[Username]\AppData\Local\Programs\Python\Python310\Lib\venv\scripts\nt) I got "No pyvenv.cfg file", so I created one with the following content in the same folder als python.exe:

dhome = C:\Users\[Username]\AppData\Local\Programs\Python\Python310\Lib\venv\scripts\nt
include-system-site-packages = false
version = 3.10.4

With cmd I was in the path where the python.exe is and called the script with:
python c:\TeslaToken\tesla-tokens.py

But then the CPU got to 100% I closed the cmd window. Then I tried it with dragging your script to pythonw.exe and immediately I had the task manager full of pythonw.exe and I shutdown the computer to stop it. It seems python.exe calls itself in a loop.

I'm much more into VB script and would try it to port your script, if you can explain me what these 3 lines do:

code_verifier = base64.urlsafe_b64encode(os.urandom(86)).rstrip(b"=")
code_challenge = base64.urlsafe_b64encode(hashlib.sha256(code_verifier).digest()).rstrip(b"=").decode("utf-8")
state = base64.urlsafe_b64encode(os.urandom(16)).rstrip(b"=").decode("utf-8")

Seems that the first line creates a random string with 86 characters, encode it with base64 and remove the equals sign on the right.

Line 2 seems to encode it with SHA256 and then with base64, but what does decode("utf-8") and digest()?

And Line 3 the same as the first, but with 16 characters and with utf8 decode.

**Comment by bntan** [comment]
To answer your questions:
- `hashlib.sha256(code_verifier).digest()` computes `code_verifier` SHA-256 hash value
- `decode("utf-8")` decodes the UTF-8 encoded byte string bytes

Authentication on TESLA uses [OAuth 2.0 (RFC6749)](https://datatracker.ietf.org/doc/html/rfc6749) [Authorization Code Flow](https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.1) with [PKCE (RFC7636)](https://datatracker.ietf.org/doc/html/rfc7636) extension to prevent CSRF and authorization code injection attacks. 

`code_verifier` and `code_challenge` computations are described in [RFC7636](https://datatracker.ietf.org/doc/html/rfc7636), [section 4.1](https://datatracker.ietf.org/doc/html/rfc7636#section-4.1) and [section 4.2](https://datatracker.ietf.org/doc/html/rfc7636#section-4.2):
- `code-verifier = 43*128unreserved` where `unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"`
- `code_challenge = BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))`

**Comment by HanSolo72** [comment]
Hi, last night I portet it to VB script and put it online. Thanks for your help. You can find it here: https://github.com/HanSolo72/TeslaTokens
